version: '3.8'

services:
  backend:
    image: alex06qf2002/examen-back  # Nombre de la imagen del backend en Docker Hub
    container_name: examen-back
    ports:
      - "8001:8001"  # Mapea el puerto 3000 del contenedor al puerto 3000 de tu máquina
    restart: always

  frontend:
    image: alex06qf2002/examen-front  # Nombre de la imagen del frontend en Docker Hub
    container_name: examen-front
    ports:
      - "80:80"  # Mapea el puerto 80 del contenedor al puerto 80 de tu máquina
    restart: always